default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: ruby_videos

development:
  <<: *default
  database: ruby_videos_development

test:
  <<: *default
  database: ruby_videos_test
