# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 120565fded1a98a6c5061b71be7dd247e1fb3d1c1c30b2c5117f9de78c26ed1df92b332ca16cc5a5f1653bc0c2d4f1d019d04761cfe1d0fe39b368525ba81174

test:
  secret_key_base: 6210c827943ff1311a9c8801d547b091bddf6b60b5cab6a7519dad085b93cdbbc294eb8ba3eac415973b2e7c5c7e31256d9fb8735b561e101d77114a18b61d35

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
